#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug          # change this option for non-debug runs
#SBATCH -N 1              # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00       # adjust the amount of time as necessary
#SBATCH -J auto-serial
#SBATCH -o auto-serial.%j.stdout
#SBATCH -e auto-serial.%j.error

rm serial.txt
srun -n 1 -c 1 ./serial -n 500 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 1000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 2000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 3000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 4000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 5000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 10000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 15000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 20000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 25000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 50000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 100000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 125000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 150000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 200000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 225000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 250000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 500000 -no -s serial.txt
./autograder -v serial -s serial.txt
